### ISSUE TITLE
TODO ChangeColorScheme

### ISSUE THREAD

**Issue by Inheritor-Vision** [Inheritor-Vision/dotfiles#9]
- [X] Improve Alacritty template calculation by using not upscaled RGB value for calculation (0-1 instead of 0-255) for more precision => Not using ColorPalette anymore
- [X] Save Result of template calculation in general in the data base to avoid recalculation. Modify template to use this values when available. Modify database to be consistent with the addition of new template over time (=> not only depends on ColorScheme version, maybe add tempalte version to only recalculate values that depends directly on  template calcualtion) => OK
- [ ] Improve Alacritty template calculation for darken & lighten or assert it is the best as it is
- [ ] Assess how ColorPalette generates values to know how to pass values for futur template that needs less values (to keep an overall coherent style)
